# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@1
  displayName: "Azure Key Vault: Get Secrets"
  inputs:
    azureSubscription: "vscode-builds-subscription"
    KeyVaultName: vscode

- task: NodeTool@0
  inputs:
    versionSpec: "14.x"

- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
  inputs:
    versionSpec: "1.x"

- script: |
    npm install -g vsce
  displayName: Install vsce

- pwsh: |
    Get-ChildItem ./i18n | ForEach-Object {
      cd $_.FullName
      vsce verify-pat -p $env:vsce_pat MS-CEINTL
    }
  env:
    vsce_pat: $(devops_pat)
