name: Lint
on: [push, pull_request]
jobs:
  lint:
    name: AutoCorrect
    runs-on: ubuntu-latest
    steps:
      - name: Check source code
        uses: actions/checkout@main

      - name: AutoCorrect Check
        uses: huacnlee/autocorrect-action@main
