on:
  push:
    branches:
      - update-localization-files-microsoft-vscode-loc-drop-* # This is the branch name pattern

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          labels: updated-translations
          delete-branch: true
